### ISSUE TITLE
Add support for parsing unix timestamps

### ISSUE THREAD

**Issue by tomzx** [tomzx/data-tracker#6]
[2015-05-28 22:11:41] production.ERROR: exception 'Exception' with message 'DateTime::__construct(): Failed to parse time string (1432865425) at position 8 (2): Unexpected character' in /path/data-tracker/vendor/compiled.php:16295
Stack trace:
#0 /path/data-tracker/vendor/compiled.php(16295): DateTime->__construct('1432865425', Object(DateTimeZone))
#1 /path/data-tracker/vendor/compiled.php(16303): Carbon\Carbon->__construct(1432865425, NULL)
#2 /path/data-tracker/app/Http/routes.php(65): Carbon\Carbon::parse(1432865425)
#3 [internal function]: App\Providers\RouteServiceProvider->{closure}()
#4 /path/data-tracker/vendor/compiled.php(7298): call_user_func_array(Object(Closure), Array)
#5 /path/data-tracker/vendor/compiled.php(7285): Illuminate\Routing\Route->runCallable(Object(Illuminate\Http\Request))
#6 /path/data-tracker/vendor/compiled.php(6954): Illuminate\Routing\Route->run(Object(Illuminate\Http\Request))
#7 [internal function]: Illuminate\Routing\Router->Illuminate\Routing{closure}(Object(Illuminate\Http\Request))
#8 /path/data-tracker/vendor/compiled.php(8952): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#9 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#10 /path/data-tracker/vendor/compiled.php(8935): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#11 /path/data-tracker/vendor/compiled.php(6955): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#12 /path/data-tracker/vendor/compiled.php(6944): Illuminate\Routing\Router->runRouteWithinStack(Object(Illuminate\Routing\Route), Object(Illuminate\Http\Request))
#13 /path/data-tracker/vendor/compiled.php(6929): Illuminate\Routing\Router->dispatchToRoute(Object(Illuminate\Http\Request))
#14 /path/data-tracker/vendor/compiled.php(1935): Illuminate\Routing\Router->dispatch(Object(Illuminate\Http\Request))
#15 [internal function]: Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http{closure}(Object(Illuminate\Http\Request))
#16 /path/data-tracker/vendor/compiled.php(8952): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 /path/data-tracker/app/Http/Middleware/Cors.php(97): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#18 /path/data-tracker/vendor/compiled.php(8944): App\Http\Middleware\Cors->handle(Object(Illuminate\Http\Request), Object(Closure))
#19 /path/data-tracker/vendor/compiled.php(12083): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#20 /path/data-tracker/vendor/compiled.php(8944): Illuminate\View\Middleware\ShareErrorsFromSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#21 /path/data-tracker/vendor/compiled.php(10785): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#22 /path/data-tracker/vendor/compiled.php(8944): Illuminate\Session\Middleware\StartSession->handle(Object(Illuminate\Http\Request), Object(Closure))
#23 /path/data-tracker/vendor/compiled.php(11789): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#24 /path/data-tracker/vendor/compiled.php(8944): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 /path/data-tracker/vendor/compiled.php(11738): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#26 /path/data-tracker/vendor/compiled.php(8944): Illuminate\Cookie\Middleware\EncryptCookies->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 /path/data-tracker/vendor/compiled.php(2478): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#28 /path/data-tracker/vendor/compiled.php(8944): Illuminate\Foundation\Http\Middleware\CheckForMaintenanceMode->handle(Object(Illuminate\Http\Request), Object(Closure))
#29 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline{closure}(Object(Illuminate\Http\Request))
#30 /path/data-tracker/vendor/compiled.php(8935): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#31 /path/data-tracker/vendor/compiled.php(1891): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#32 /path/data-tracker/vendor/compiled.php(1880): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#33 /path/data-tracker/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#34 {main}

**Comment by tomzx** [comment]
Added @ b4227bc30fcbc23fd5bad4da180f396de53ab642.
